import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const filePath = path.resolve(__dirname, '..', 'src/utils/i18n.ts');

const categoryTranslations = {
  // Basic converter categories (English only)
  'length': { 'en': 'Length Converter' },
  'weight-mass': { 'en': 'Weight & Mass Converter' },
  'temperature': { 'en': 'Temperature Converter' },
  'area': { 'en': 'Area Converter' },
  'volume': { 'en': 'Volume Converter' },
  'speed': { 'en': 'Speed Converter' },
  'time': { 'en': 'Time Converter' },
  'currency': { 'en': 'Currency Converter' },
  'binary': { 'en': 'Binary Converter' },

  // Converters
  'pressure': {
    'en': 'Pressure Converter', 'es': 'Conversor de Presión', 'hi': 'दबाव कनवर्टर', 'fr': 'Convertisseur de Pression', 'pt': 'Conversor de Pressão', 'de': 'Druck-Umrechner', 'ar': 'محول الضغط', 'ja': '圧力変換器',
    'zh-cn': '压力转换器', 'zh-tw': '壓力轉換器', 'ru': 'Конвертер давления', 'it': 'Convertitore di pressione', 'nl': 'Druk omrekenen', 'tr': 'Basınç Dönüştürücü', 'ko': '압력 변환기', 'id': 'Konverter Tekanan', 'vi': 'Bộ chuyển đổi áp suất', 'th': 'เครื่องแปลงแรงดัน', 'pl': 'Konwerter ciśnienia', 'uk': 'Конвертер тиску', 'ro': 'Convertor de presiune', 'el': 'Μετατροπέας πίεσης', 'sv': 'Tryckkonverterare', 'no': 'Trykkonverterer', 'da': 'Trykomregner', 'fi': 'Paineenmuunnin', 'cs': 'Převodník tlaku', 'hu': 'Nyomás átváltó', 'he': 'ממיר לחץ', 'ms': 'Penukar Tekanan', 'bn': 'চাপ রূপান্তরকারী', 'ta': 'அழுத்தம் மாற்றி', 'te': 'పీడనం మార్పిడి', 'mr': 'दाब कनवर्टर', 'gu': 'દબાણ કન્વર્ટર', 'pa': 'ਦਬਾਅ ਕਨਵਰਟਰ', 'ur': 'دباؤ کنورٹر', 'fa': 'مبدل فشار', 'tl': 'Tagasalin ng Presyon'
  },
  'energy': {
    'en': 'Energy Converter', 'es': 'Conversor de Energía', 'hi': 'ऊर्जा कनवर्टर', 'fr': "Convertisseur d'Énergie", 'pt': 'Conversor de Energia', 'de': 'Energie-Umrechner', 'ar': 'محول الطاقة', 'ja': 'エネルギー変換器',
    'zh-cn': '能量转换器', 'zh-tw': '能量轉換器', 'ru': 'Конвертер энергии', 'it': 'Convertitore di energia', 'nl': 'Energie omrekenen', 'tr': 'Enerji Dönüştürücü', 'ko': '能量 변환기', 'id': 'Konverter Energi', 'vi': 'Bộ chuyển đổi năng lượng', 'th': 'เครื่องแปลงพลังงาน', 'pl': 'Konwerter energii', 'uk': 'Конвертер енергії', 'ro': 'Convertor de energie', 'el': 'Μετατροπέας ενέργειας', 'sv': 'Energikonverterare', 'no': 'Energikonverterer', 'da': 'Energiomregner', 'fi': 'Energianmuunnin', 'cs': 'Převodník energie', 'hu': 'Energia átváltó', 'he': 'ממיר אנרגיה', 'ms': 'Penukar Tenaga', 'bn': 'শক্তি রূপান্তরকারী', 'ta': 'சக்தி மாற்றி', 'te': 'శక్తి మార్పిడి', 'mr': 'ऊर्जा कनवर्टर', 'gu': 'ઉર્જા કન્વર્ટર', 'pa': 'ਊਰਜા ਕਨਵਰਟਰ', 'ur': 'توانائی کنورٹر', 'fa': 'مبدل انرژی', 'tl': 'Tagasalin ng Enerhiya'
  },
  'power': {
    'en': 'Power Converter', 'es': 'Conversor de Potencia', 'hi': 'शक्ति कनवर्टर', 'fr': 'Convertisseur de Puissance', 'pt': 'Conversor de Potência', 'de': 'Leistungs-Umrechner', 'ar': 'محول القدرة', 'ja': '電力変換器',
    'zh-cn': '功率转换器', 'zh-tw': '功率轉換器', 'ru': 'Конвертер мощности', 'it': 'Convertitore di potenza', 'nl': 'Leistungs-Umrechner', 'tr': 'Güç Dönüştürücü', 'ko': '전력 변환기', 'id': 'Konverter Daya', 'vi': 'Bộ chuyển đổi công suất', 'th': 'เครื่องแปลงกำลังไฟฟ้า', 'pl': 'Konwerter mocy', 'uk': 'Конвертер потужності', 'ro': 'Convertor de putere', 'el': 'Μετατροπέας ισχύος', 'sv': 'Effektkonverterare', 'no': 'Effektkonverterer', 'da': 'Effektomregner', 'fi': 'Tehonmuunnin', 'cs': 'Převodník výkonu', 'hu': 'Teljesítmény átváltó', 'he': 'ממיר הספק', 'ms': 'Penukar Kuasa', 'bn': 'ক্ষমতা রূপান্তরকারী', 'ta': 'சக்தி மாற்றி', 'te': 'శక్తి మార్పిడి', 'mr': 'पॉवर कनवर्टर', 'gu': 'પાવર કન્વર્ટર', 'pa': 'ਪਾਵਰ ਕਨਵਰਟਰ', 'ur': 'طاقت کنورٹر', 'fa': 'مبدل توان', 'tl': 'Tagasalin ng Lakas'
  },
  'data-storage': {
    'en': 'Data Storage Converter', 'es': 'Conversor de Almacenamiento', 'hi': 'डेटा स्टोरेज कनवर्टर', 'fr': 'Stockage de Données', 'pt': 'Armazenamento de Dados', 'de': 'Datenspeicher-Umrechner', 'ar': 'محول تخزين البيانات', 'ja': 'データストレージ変換器',
    'zh-cn': '数据存储转换器', 'zh-tw': '數據儲存轉換器', 'ru': 'Накопители данных', 'it': 'Archiviazione dati', 'nl': 'Gegevensopslag omrekenen', 'tr': 'Veri Depolama Dönüştürücü', 'ko': '데이터 저장 공간 변환기', 'id': 'Konverter Penyimpanan Data', 'vi': 'Bộ chuyển đổi lưu trữ dữ liệu', 'th': 'เครื่องแปลงพื้นที่เก็บข้อมูล', 'pl': 'Konwerter pamięci danych', 'uk': 'Конвертер обсягу даних', 'ro': 'Convertor de stocare date', 'el': 'Μετατροπέας αποθήκευσης δεδομένων', 'sv': 'Datakonverterare', 'no': 'Datakonverterer', 'da': 'Dataomregner', 'fi': 'Tiedonsiirtomuunnin', 'cs': 'Převodník datových úložišť', 'hu': 'Adattárolás átváltó', 'he': 'ממיר אחסון נתונים', 'ms': 'Penukar Penyimpanan Data', 'bn': 'ডেটা স্টোরেজ রূপান্তরকারী', 'ta': 'தரவு சேமிப்பு மாற்றி', 'te': 'డేటా నిల్వ మార్పిడి', 'mr': 'डेटा स्टोरेज कनवर्टर', 'gu': 'ડેટા સ્ટોરેજ કન્વર્ટર', 'pa': 'ਡਾਟਾ ਸਟੋਰੇਜ ਕਨਵਰਟਰ', 'ur': 'ڈیٹا اسٹوریج کنورٹر', 'fa': 'مبدل ذخیره‌سازی داده', 'tl': 'Tagasalin ng Imbakan ng Data'
  },
  'angle': {
    'en': 'Angle Converter', 'es': 'Conversor de Ángulos', 'hi': 'कोण कनवर्टर', 'fr': "Convertisseur d'Angles", 'pt': 'Conversor de Ângulo', 'de': 'Winkel-Umrechner', 'ar': 'محول الزوايا', 'ja': '角度変換器',
    'zh-cn': '角度转换器', 'zh-tw': '角度轉換器', 'ru': 'Конвертер углов', 'it': 'Convertitore di angoli', 'nl': 'Hoeken omrekenen', 'tr': 'Açı Dönüştürücü', 'ko': '각도 변환기', 'id': 'Konverter Sudut', 'vi': 'Bộ chuyển đổi góc', 'th': 'เครื่องแปลงมุม', 'pl': 'Konwerter kątów', 'uk': 'Конвертер кутів', 'ro': 'Convertor de unghiuri', 'el': 'Μετατροπέας γωνιών', 'sv': 'Vinkelkonverterare', 'no': 'Vinkelkonverterer', 'da': 'Vinkelomregner', 'fi': 'Kulmanmuunnin', 'cs': 'Převodník úhlů', 'hu': 'Szög átváltó', 'he': 'ממיר זוויות', 'ms': 'Penukar Sudut', 'bn': 'কোণ রূপান্তরকারী', 'ta': 'கோணம் மாற்றி', 'te': 'కోణం మార్పిడి', 'mr': 'कोण कनवर्टर', 'gu': 'ખૂણો કન્વર્ટર', 'pa': 'ਕੋਣ ਕਨਵਰਟਰ', 'ur': 'زاویہ کنورٹر', 'fa': 'مبدل زاویه', 'tl': 'Tagasalin ng Angulo'
  },
  'frequency': {
    'en': 'Frequency Converter', 'es': 'Conversor de Frecuencia', 'hi': 'आवृत्ति कनवर्टर', 'fr': 'Convertisseur de Fréquence', 'pt': 'Conversor de Frequência', 'de': 'Frequenz-Umrechner', 'ar': 'محول التردد', 'ja': '周波数変換器',
    'zh-cn': '频率转换器', 'zh-tw': '頻率轉換器', 'ru': 'Конвертер частоты', 'it': 'Convertitore di frequenza', 'nl': 'Frequentie omrekenen', 'tr': 'Frekans Dönüştürücü', 'ko': '주파수 변환기', 'id': 'Konverter Frekuensi', 'vi': 'Bộ chuyển đổi tần số', 'th': 'เครื่องแปลงความถี่', 'pl': 'Konwerter częstotliwości', 'uk': 'Конвертер частоти', 'ro': 'Convertor de frecvență', 'el': 'Μετατροπέας συχνότητας', 'sv': 'Frekvenskonverterare', 'no': 'Frekvenskonverterer', 'da': 'Frekvensomregner', 'fi': 'Taajuudenmuunnin', 'cs': 'Převodník frekvence', 'hu': 'Frekvencia átváltó', 'he': 'ממיר תדרים', 'ms': 'Penukar Frekuensi', 'bn': 'ফ্রিকোয়েন্সি রূপান্তরকারী', 'ta': 'அதிர்வெண் மாற்றி', 'te': 'ఫ్రీక్వెన్సీ మార్పిడి', 'mr': 'वारंवारता कनवर्टर', 'gu': 'આવર્તન કન્વર્ટર', 'pa': 'आवृत्ति कनवर्टर', 'ur': 'فریکوئنسی کنورٹر', 'fa': 'مبدل فرکانس', 'tl': 'Tagasalin ng Dalas'
  },
  'fuel-consumption': {
    'en': 'Fuel Consumption Converter', 'es': 'Conversor de Consumo', 'hi': 'ईंधन खपत कनवर्टर', 'fr': 'Consommation de Carburant', 'pt': 'Consumo de Combustível', 'de': 'Kraftstoffverbrauch-Umrechner', 'ar': 'محول استهلاك الوقود', 'ja': '燃料消費量変換器',
    'zh-cn': '油耗转换器', 'zh-tw': '油耗轉換器', 'ru': 'Расход топлива', 'it': 'Consumo carburante', 'nl': 'Brandstofverbruik omrekenen', 'tr': 'Yakıt Tüketimi Dönüştürücü', 'ko': '연비 변환기', 'id': 'Konverter Konsumsi Bahan Bakar', 'vi': 'Bộ chuyển đổi tiêu thụ nhiên liệu', 'th': 'เครื่องแปลงการใช้เชื้อเพลิง', 'pl': 'Konwerter zużycia paliwa', 'uk': 'Конвертер витрати палива', 'ro': 'Convertor consum combustibil', 'el': 'Μετατροπέας κατανάλωσης καυσίμου', 'sv': 'Bränslekonverterare', 'no': 'Drivstoffkonverterer', 'da': 'Brændstofomregner', 'fi': 'Polttoaineenkulutusmuunnin', 'cs': 'Převodník spotřeby paliva', 'hu': 'Üzemanyag-fogyasztás átváltó', 'he': 'ממיר תצרוכת דלק', 'ms': 'Penukar Penggunaan Bahan Bakar', 'bn': 'জ্বালানী খরচ রূপান্তরকারী', 'ta': 'எரிபொருள் நுகர்வு மாற்றி', 'te': 'ఇంధన వినియోగ మార్పిడి', 'mr': 'इंधन वापर कनवर्टर', 'gu': 'બળતણ વપરાશ કન્વર્ટર', 'pa': 'ਬਾਲਣ ਦੀ ਖਪਤ ਕਨਵਰਟਰ', 'ur': 'ایندھن کی کھپت کنورٹر', 'fa': 'مبدل مصرف سوخت', 'tl': 'Tagasalin ng Konsumo ng Fuel'
  },
  'force': {
    'en': 'Force Converter', 'es': 'Conversor de Fuerza', 'hi': 'बल कनवर्टर', 'fr': 'Convertisseur de Force', 'pt': 'Conversor de Força', 'de': 'Kraft-Umrechner', 'ar': 'محول القوة', 'ja': '力変換器',
    'zh-cn': '力转换器', 'zh-tw': '力轉換器', 'ru': 'Конвертер силы', 'it': 'Convertitore di forza', 'nl': 'Kracht omrekenen', 'tr': 'Kuvvet Dönüştürücü', 'ko': '힘 변환기', 'id': 'Konverter Gaya', 'vi': 'Bộ chuyển đổi lực', 'th': 'เครื่องแปลงแรง', 'pl': 'Konwerter siły', 'uk': 'Конвертер сили', 'ro': 'Convertor de forță', 'el': 'Μετατροπέας δύναμης', 'sv': 'Kraftkonverterare', 'no': 'Kraftkonverterer', 'da': 'Kraftomregner', 'fi': 'Voimanmuunnin', 'cs': 'Převodník síly', 'hu': 'Erő átváltó', 'he': 'ממיר כוחות', 'ms': 'Penukar Daya', 'bn': 'বল রূপান্তরকারী', 'ta': 'விசை மாற்றி', 'te': 'బలం మార్పిడి', 'mr': 'बल कनवर्टर', 'gu': 'બળ કન્વર્ટર', 'pa': 'ਬਲ ਕਨਵਰਟਰ', 'ur': 'طاقت کنورٹر', 'fa': 'مبدل نیرو', 'tl': 'Tagasalin ng Lakas'
  },
  'torque': {
    'en': 'Torque Converter', 'es': 'Conversor de Torque', 'hi': 'टॉर्क कनवर्टर', 'fr': 'Convertisseur de Couple', 'pt': 'Conversor de Torque', 'de': 'Drehmoment-Umrechner', 'ar': 'محول عزم الدوران', 'ja': 'トルク変換器',
    'zh-cn': '扭矩转换器', 'zh-tw': '扭矩轉換器', 'ru': 'Крутящий момент', 'it': 'Convertitore di coppia', 'nl': 'Draaimoment omrekenen', 'tr': 'Tork Dönüştürücü', 'ko': '토크 변환기', 'id': 'Konverter Torsi', 'vi': 'Bộ chuyển đổi mô-men xoắn', 'th': 'เครื่องแปลงแรงบิด', 'pl': 'Konwerter momentu obrotowego', 'uk': 'Конвертер крутного моменту', 'ro': 'Convertor de cuplu', 'el': 'Μετατροπέας ροπής', 'sv': 'Vridmomentskonverterare', 'no': 'Dreiemomentkonverterer', 'da': 'Momentomregner', 'fi': 'Vääntömomenttimuunnin', 'cs': 'Převodník točivého momentu', 'hu': 'Forgatónyomaték átváltó', 'he': 'ממיר מומנט', 'ms': 'Penukar Tork', 'bn': 'টর্ক রূপান্তরকারী', 'ta': 'முறுக்கு மாற்றி', 'te': 'టార్క్ మార్పిడి', 'mr': 'टॉर्क कनवर्टर', 'gu': 'ટોર્ક કન્વર્ટર', 'pa': 'ਟਾਰਕ ਕਨਵਰਟਰ', 'ur': 'ٹارک کنورٹر', 'fa': 'مبدل گشتاور', 'tl': 'Tagasalin ng Torque'
  },
  'density': {
    'en': 'Density Converter', 'es': 'Conversor de Densidad', 'hi': 'घनत्व कनवर्टर', 'fr': 'Convertisseur de Densité', 'pt': 'Conversor de Densidade', 'de': 'Dichte-Umrechner', 'ar': 'محول الكثافة', 'ja': '密度変換器',
    'zh-cn': '密度转换器', 'zh-tw': '密度轉換器', 'ru': 'Конвертер плотности', 'it': 'Convertitore di densità', 'nl': 'Dichtheid omrekenen', 'tr': 'Yoğunluk Dönüştürücü', 'ko': '밀도 변환기', 'id': 'Konverter Kepadatan', 'vi': 'Bộ chuyển đổi mật độ', 'th': 'เครื่องแปลงความหนาแน่น', 'pl': 'Konwerter gęstości', 'uk': 'Конвертер щільності', 'ro': 'Convertor de densitate', 'el': 'Μετατροπέας πυκνότητας', 'sv': 'Densitetskonverterare', 'no': 'Tetthetskonverterer', 'da': 'Massefyldeomregner', 'fi': 'Tiheysmuunnin', 'cs': 'Převodník hustoty', 'hu': 'Sűrűség átváltó', 'he': 'ממיר צפיפות', 'ms': 'Penukar Ketumpatan', 'bn': 'ঘনত্ব রূপান্তরকারী', 'ta': 'அடர்த்தி மாற்றி', 'te': 'సాంద్రత మార్పిడి', 'mr': 'घनत्व कनवर्टर', 'gu': 'ઘનતા કન્વર્ટર', 'pa': 'ઘনતા કન્વર્ટર', 'ur': 'کثافت کنورٹر', 'fa': 'مبدل چگالی', 'tl': 'Tagasalin ng Density'
  },
  'flow-rate': {
    'en': 'Flow Rate Converter', 'es': 'Conversor de Caudal', 'hi': 'प्रवाह दर कनवर्टर', 'fr': 'Convertisseur de Débit', 'pt': 'Conversor de Vazão', 'de': 'Durchflussrate-Umrechner', 'ar': 'محول معدل التدفق', 'ja': '流量変換器',
    'zh-cn': '流量转换器', 'zh-tw': '流量轉換器', 'ru': 'Расход жидкости', 'it': 'Portata volumetrica', 'nl': 'Debiet omrekenen', 'tr': 'Debi Dönüştürücü', 'ko': '유량 변환기', 'id': 'Konverter Laju Aliran', 'vi': 'Bộ chuyển đổi tốc độ dòng chảy', 'th': 'เครื่องแปลงอัตราการไหล', 'pl': 'Konwerter natężenia przepływu', 'uk': 'Конвертер витрати', 'ro': 'Convertor debit', 'el': 'Μετατροπέας ρυθμού ροής', 'sv': 'Flödeskonverterare', 'no': 'Væskestrømkonverterer', 'da': 'Flowomregner', 'fi': 'Virtausmuunnin', 'cs': 'Převodník průtoku', 'hu': 'Áramlási sebesség átváltó', 'he': 'ממיר קצב זרימה', 'ms': 'Penukar Kadar Aliran', 'bn': 'প্রবাহ হার রূপান্তরকারী', 'ta': 'பாய்வு வீதம் மாற்றி', 'te': 'ప్రవాహం రేటు మార్పిడి', 'mr': 'प्रवाह दर कनवर्टर', 'gu': 'પ્રવાહ દર કન્વર્ટર', 'pa': 'ਪ੍ਰਵਾਹ ਦਰ ਕਨਵਰਟਰ', 'ur': 'بہاؤ کی شرح کنورٹر', 'fa': 'مبدل نرخ جریان', 'tl': 'Tagasalin ng Flow Rate'
  },
  'voltage': {
    'en': 'Voltage Converter', 'es': 'Conversor de Voltaje', 'hi': 'वोल्टेज कनवर्टर', 'fr': 'Convertisseur de Tension', 'pt': 'Conversor de Tensão', 'de': 'Spannung-Umrechner', 'ar': 'محول الجهد الكهربائي', 'ja': '電圧変換器',
    'zh-cn': '电压转换器', 'zh-tw': '電壓轉換器', 'ru': 'Конвертер напряжения', 'it': 'Convertitore di tensione', 'nl': 'Spanning omrekenen', 'tr': 'Voltaj Dönüştürücü', 'ko': '전압 변환기', 'id': 'Konverter Tegangan', 'vi': 'Bộ chuyển đổi điện áp', 'th': 'เครื่องแปลงแรงดันไฟฟ้า', 'pl': 'Konwerter napięcia', 'uk': 'Конвертер напруги', 'ro': 'Convertor de tensiune', 'el': 'Μετατροπέας τάσης', 'sv': 'Spänningskonverterare', 'no': 'Spenningskonverterer', 'da': 'Spændingsomregner', 'fi': 'Jännitemuunnin', 'cs': 'Převodník napětí', 'hu': 'Feszültség átváltó', 'he': 'ממיר מתח', 'ms': 'Penukar Voltan', 'bn': 'ভোল্টেজ রূপান্তরকারী', 'ta': 'மின்னழுத்தம் மாற்றி', 'te': 'వోల్టేజ్ మార్పిడి', 'mr': 'वोल्टेज कनवर्टर', 'gu': 'વોલ્ટેજ કન્વર્ટર', 'pa': 'ਵੋਲਟੇਜ ਕਨਵਰਟਰ', 'ur': 'وولٹیج کنورٹر', 'fa': 'مبدل ولتاژ', 'tl': 'Tagasalin ng Boltahe'
  },
  'current': {
    'en': 'Current Converter', 'es': 'Conversor de Corriente', 'hi': 'धारा कनवर्टर', 'fr': 'Convertisseur de Courant', 'pt': 'Conversor de Corrente', 'de': 'Strom-Umrechner', 'ar': 'محول التيار', 'ja': '電流変換器',
    'zh-cn': '电流转换器', 'zh-tw': '電流轉換器', 'ru': 'Сила тока', 'it': 'Corrente elettrica', 'nl': 'Stroomsterkte omrekenen', 'tr': 'Akım Dönüştürücü', 'ko': '전류 변환기', 'id': 'Konverter Arus', 'vi': 'Bộ chuyển đổi dòng điện', 'th': 'เครื่องแปลงกระแสไฟฟ้า', 'pl': 'Konwerter prądu', 'uk': 'Конвертер струму', 'ro': 'Convertor curent electric', 'el': 'Μετατροπέας έντασης ρεύματος', 'sv': 'Strömkonverterare', 'no': 'Strømkonverterer', 'da': 'Strømomregner', 'fi': 'Sähkövirtamuunnin', 'cs': 'Převodník elektrického proudu', 'hu': 'Áramerősség átváltó', 'he': 'ממיר זרם', 'ms': 'Penukar Arus', 'bn': 'কারেন্ট রূপান্তরকারী', 'ta': 'மின்னோட்டம் மாற்றி', 'te': 'కరెంట్ మార్పిడి', 'mr': 'प्रवाह कनवर्टर', 'gu': 'પ્રવાહ કન્વર્ટર', 'pa': 'ਕਰੰਟ ਕਨਵਰਟਰ', 'ur': 'کرنٹ کنورٹر', 'fa': 'مبدل جریان الکتریکی', 'tl': 'Tagasalin ng Kuryente'
  },
  'resistance': {
    'en': 'Resistance Converter', 'es': 'Conversor de Resistencia', 'hi': 'प्रतिरोध कनवर्टर', 'fr': 'Convertisseur de Résistance', 'pt': 'Conversor de Resistência', 'de': 'Widerstand-Umrechner', 'ar': 'محول المقاومة', 'ja': '抵抗変換器',
    'zh-cn': '电阻转换器', 'zh-tw': '電阻轉換器', 'ru': 'Сопротивление', 'it': 'Resistenza elettrica', 'nl': 'Weerstand omrekenen', 'tr': 'Direnç Dönüştürücü', 'ko': '저항 변환기', 'id': 'Konverter Hambatan', 'vi': 'Bộ chuyển đổi điện trở', 'th': 'เครื่องแปลงความต้านทาน', 'pl': 'Konwerter rezystancji', 'uk': 'Конвертер опору', 'ro': 'Convertor rezistență', 'el': 'Μετατροπέας αντίστασης', 'sv': 'Resistanskonverterare', 'no': 'Motstandskonverterer', 'da': 'Modstandsomregner', 'fi': 'Resistanssimuunnin', 'cs': 'Převodník odporu', 'hu': 'Ellenállás átváltó', 'he': 'ממיר התנגדות', 'ms': 'Penukar Rintangan', 'bn': 'প্রতিরোধ রূপান্তরকারী', 'ta': 'மின்தடை மாற்றி', 'te': 'నిరోధకత మార్పిడి', 'mr': 'अवरोध कनवर्टर', 'gu': 'અવરોધ કન્વર્ટર', 'pa': 'ਪ੍ਰਤੀਰੋਧ ਕਨਵਰਟਰ', 'ur': 'مزاحمت کنورٹر', 'fa': 'مبدل مقاومت الکتریکی', 'tl': 'Tagasalin ng Resistance'
  },
  'capacitance': {
    'en': 'Capacitance Converter', 'es': 'Conversor de Capacitancia', 'hi': 'धारिता कनवर्टर', 'fr': 'Capacitance', 'pt': 'Capacitância', 'de': 'Kapazitäts-Umrechner', 'ar': 'محول السعة الكهربائية', 'ja': '静電容量変換器',
    'zh-cn': '电容转换器', 'zh-tw': '電容轉換器', 'ru': 'Электрическая емкость', 'it': 'Capacità elettrica', 'nl': 'Capaciteit omrekenen', 'tr': 'Kapasitans Dönüştürücü', 'ko': '정전용량 변환기', 'id': 'Konverter Kapasitansi', 'vi': 'Bộ chuyển đổi điện dung', 'th': 'เครื่องแปลงความจุไฟฟ้า', 'pl': 'Konwerter pojemności elektrycznej', 'uk': 'Конвертер ємності', 'ro': 'Convertor capacitate electrică', 'el': 'Μετατροπέας χωρητικότητας', 'sv': 'Kapacitanskonverterare', 'no': 'Kapasitanskonverterer', 'da': 'Kapacitansomregner', 'fi': 'Kapasitanssimuunnin', 'cs': 'Převodník kapacity', 'hu': 'Kapacitás átváltó', 'he': 'ממיר קיבול', 'ms': 'Penukar Kapasitans', 'bn': 'ক্যাপাসিট্যান্স রূপান্তরকারী', 'ta': 'மின் கொள்ளளவு மாற்றி', 'te': 'కెపాసిటెన్స్ మార్పిడి', 'mr': 'कॅपेसिटन्स कनवर्टर', 'gu': 'કેપેસિટન્સ કન્વર્ટર', 'pa': 'ਕੈਪੇਸਿਟੈਂਸ ਕਨਵਰਟਰ', 'ur': 'گنجائش کنورٹر', 'fa': 'مبدل ظرفیت خازنی', 'tl': 'Tagasalin ng Capacitance'
  },
  'inductance': {
    'en': 'Inductance Converter', 'es': 'Conversor de Inductancia', 'hi': 'प्रेरकत्व कनवर्टर', 'fr': "Convertisseur d'Inductance", 'pt': 'Conversor de Indutância', 'de': 'Induktivitäts-Umrechner', 'ar': 'محول المحاثة', 'ja': 'インダクタンス変換器',
    'zh-cn': '电感转换器', 'zh-tw': '電感轉換器', 'ru': 'Индуктивность', 'it': 'Induttanza elettrica', 'nl': 'Inductie omrekenen', 'tr': 'Endüktans Dönüştürücü', 'ko': '인덕턴스 변환기', 'id': 'Konverter Induktansi', 'vi': 'Bộ chuyển đổi độ tự cảm', 'th': 'เครื่องแปลงความเหนี่ยวนำ', 'pl': 'Konwerter indukcyjności', 'uk': 'Конвертер індуктивності', 'ro': 'Convertor inductanță', 'el': 'Μετατροπέας αυτεπαγωγής', 'sv': 'Induktanskonverterare', 'no': 'Induktanskonverterer', 'da': 'Induktansomregner', 'fi': 'Induktanssimuunnin', 'cs': 'Převodník indukčnosti', 'hu': 'Induktivitás átváltó', 'he': 'ממיר השראות', 'ms': 'Penukar Induktans', 'bn': 'ইন্ডাক্ট্যান্স রূপান্তরকারী', 'ta': 'மின் தூண்டு மாற்றி', 'te': 'ఇండక్టెన్స్ మార్పిడి', 'mr': 'इंडक्टन्स कनवर्टर', 'gu': 'ઇન્ડક્ટન્સ કન્વર્ટર', 'pa': 'ਇੰਡਕਟੈਂਸ ਕਨਵਰਟਰ', 'ur': 'انڈکٹنس کنورٹر', 'fa': 'مبدل القاگر', 'tl': 'Tagasalin ng Inductance'
  },
  'data-transfer-rate': {
    'en': 'Data Transfer Rate Converter', 'es': 'Tasa de Transferencia', 'hi': 'डेटा ट्रांसफर दर कनवर्टर', 'fr': 'Taux de Transfert de Données', 'pt': 'Taxa de Transferência de Dados', 'de': 'Datenübertragungsrate-Umrechner', 'ar': 'محول معدل نقل البيانات', 'ja': 'データ転送速度変換器',
    'zh-cn': '数据传输率转换器', 'zh-tw': '數據傳輸率轉換器', 'ru': 'Скорость передачи данных', 'it': 'Velocità di trasmissione', 'nl': 'Datatransfersnelheid omrekenen', 'tr': 'Veri Transfer Hızı Dönüştürücü', 'ko': '데이터 전송 속도 변환기', 'id': 'Konverter Laju Transfer Data', 'vi': 'Bộ chuyển đổi tốc độ truyền dữ liệu', 'th': 'เครื่องแปลงอัตราการส่งข้อมูล', 'pl': 'Konwerter szybkości transferu danych', 'uk': 'Конвертер швидкості передачі', 'ro': 'Convertor rată transfer date', 'el': 'Μετατροπέας ρυθμού μεταφοράς δεδομένων', 'sv': 'Dataöverföringskonverterare', 'no': 'Dataoverføringskonverterer', 'da': 'Dataoverførselshastighedsomregner', 'fi': 'Tiedonsiirtonopeusmuunnin', 'cs': 'Převodník rychlosti přenosu dat', 'hu': 'Adatátviteli sebesség átváltó', 'he': 'ממיר קצב העברת נתונים', 'ms': 'Penukar Kadar Pemindahan Data', 'bn': 'ডেটা ট্রান্সফার রেট রূপান্তরকারী', 'ta': 'தரவு பரிமாற்ற வீதம் மாற்றி', 'te': 'డేటా బదిలీ రేటు మార్పిడి', 'mr': 'डेटा ट्रान्सफर रेट कनवर्टर', 'gu': 'ડેટા ટ્રાન્સફર રેટ કન્વર્ટર', 'pa': 'ਡਾਟਾ ਟ੍ਰਾਂਸਫਰ ਰੇਟ ਕਨਵਰਟਰ', 'ur': 'ڈیٹا ٹرانسفر ریٹ کنورٹر', 'fa': 'مبدل نرخ انتقال داده', 'tl': 'Tagasalin ng Data Transfer Rate'
  },
  'bandwidth': {
    'en': 'Bandwidth Converter', 'es': 'Conversor de Ancho de Banda', 'hi': 'बैंडविड्थ कनवर्टर', 'fr': 'Convertisseur de Bande Passante', 'pt': 'Conversor de Largura de Banda', 'de': 'Bandbreiten-Umrechner', 'ar': 'محول عرض النطاق الترددي', 'ja': '帯域幅変換器',
    'zh-cn': '带宽转换器', 'zh-tw': '頻寬轉換器', 'ru': 'Ширина канала', 'it': 'Larghezza di banda', 'nl': 'Bandbreedte omrekenen', 'tr': 'Bant Genişliği Dönüştürücü', 'ko': '대역폭 변환기', 'id': 'Konverter Bandwidth', 'vi': 'Bộ chuyển đổi băng thông', 'th': 'เครื่องแปลงแบนด์วิดท์', 'pl': 'Konwerter szerokości pasma', 'uk': 'Конвертер пропускної здатності', 'ro': 'Convertor lățime de bandă', 'el': 'Μετατροπέας εύρους ζώνης', 'sv': 'Bandbreddskonverterare', 'no': 'Båndbreddekonverterer', 'da': 'Båndbreddeomregner', 'fi': 'Kaistanleveysmuunnin', 'cs': 'Převodník šířky pásma', 'hu': 'Sávszélesség átváltó', 'he': 'ממיר רוחב פס', 'ms': 'Penukar Jalur Lebar', 'bn': 'ব্যান্ডউইথ রূপান্তরকারী', 'ta': 'அலைவரிசை மாற்றி', 'te': 'బ్యాండ్‌విడ్త్ మార్పిడి', 'mr': 'बॅंडविड्थ कनवर्टर', 'gu': 'બેન્ડવિડ્થ કન્વર્ટર', 'pa': 'ਬੈਂਡਵਿਡਥ ਕਨਵਰਟਰ', 'ur': 'بینڈوتھ کنورٹر', 'fa': 'مبدل پهنای باند', 'tl': 'Tagasalin ng Bandwidth'
  },
  'radiation': {
    'en': 'Radiation Converter', 'es': 'Conversor de Radiación', 'hi': 'विकिरण कनवर्टर', 'fr': 'Convertisseur de Radiations', 'pt': 'Conversor de Radiação', 'de': 'Strahlungs-Umrechner', 'ar': 'محول الإشعاع', 'ja': '放射線変換器',
    'zh-cn': '辐射转换器', 'zh-tw': '輻射轉換器', 'ru': 'Радиационный конвертер', 'it': 'Convertitore di radiazioni', 'nl': 'Straling omrekenen', 'tr': 'Radyasyon Dönüştürücü', 'ko': '방사선 변환기', 'id': 'Konverter Radiasi', 'vi': 'Bộ chuyển đổi bức xạ', 'th': 'เครื่องแปลงรังสี', 'pl': 'Konwerter promieniowania', 'uk': 'Конвертер радіації', 'ro': 'Convertor de radiații', 'el': 'Μετατροπέας ραδιενέργειας', 'sv': 'Strålningskonverterare', 'no': 'Strålingskonverterer', 'da': 'Strålingsomregner', 'fi': 'Säteilynmuunnin', 'cs': 'Převodník radiace', 'hu': 'Sugárzás átváltó', 'he': 'ממיר קרינה', 'ms': 'Penukar Radiasi', 'bn': 'বিকিরণ রূপান্তরকারী', 'ta': 'கதிர்வீச்சு மாற்றி', 'te': 'రేడియేషన్ మార్పిడి', 'mr': 'रेडिएशन कनवर्टर', 'gu': 'રેડિયેશન કન્વર્ટર', 'pa': 'ਵਿਕਿਰਣ ਕਨਵਰਟਰ', 'ur': 'تابکاری کنورٹر', 'fa': 'مبدل پرتو', 'tl': 'Tagasalin ng Radiation'
  },
  'heat': {
    'en': 'Heat Transfer Converter', 'es': 'Transferencia de Calor', 'hi': 'ऊष्मा स्थानांतरण कनवर्टर', 'fr': 'Transfert de Chaleur', 'pt': 'Transferência de Calor', 'de': 'Wärmeübertragungs-Umrechner', 'ar': 'محول انتقال الحرارة', 'ja': '熱伝導率変換器',
    'zh-cn': '传热转换器', 'zh-tw': '傳熱轉換器', 'ru': 'Теплопроводность', 'it': 'Scambio termico', 'nl': 'Warmteoverdracht omrekenen', 'tr': 'Isı Transferi Dönüştürücü', 'ko': '열전달 변환기', 'id': 'Konverter Perpindahan Panas', 'vi': 'Bộ chuyển đổi truyền nhiệt', 'th': 'เครื่องแปลงการถ่ายเทความร้อน', 'pl': 'Konwerter przewodności cieplnej', 'uk': 'Конвертер теплопровідності', 'ro': 'Convertor transfer de căldură', 'el': 'Μετατροπέας μετάδοσης θερμότητας', 'sv': 'Värmekonverterare', 'no': 'Varmeoverføringskonverterer', 'da': 'Varmeoverførselsomregner', 'fi': 'Lämmönsiirtomuunnin', 'cs': 'Převodník přenosu tepla', 'hu': 'Hőátadás átváltó', 'he': 'ממיר מעבר חום', 'ms': 'Penukar Pemindahan Haba', 'bn': 'তাপ স্থানান্তর রূপান্তরকারী', 'ta': 'வெப்ப பரிமாற்ற மாற்றி', 'te': 'ఉష్ణ బదిలీ మార్పిడి', 'mr': 'हीट ट्रान्सफर कनवर्टर', 'gu': 'હીટ ટ્રાન્સફર કન્વર્ટર', 'pa': 'ਗਰਮੀ ਟ੍ਰਾਂਸਫਰ ਕਨਵਰਟਰ', 'ur': 'حرارت کی منتقلی کنورٹر', 'fa': 'مبدل انتقال حرارت', 'tl': 'Tagasalin ng Heat Transfer'
  },
  'engineering': {
    'en': 'Engineering Converters', 'es': 'Conversor de Ingeniería', 'hi': 'इंजीनियरिंग कनवर्टर्स', 'fr': "Convertisseurs d'Ingénierie", 'pt': 'Conversores de Engenharia', 'de': 'Ingenieur-Umrechner', 'ar': 'محولات الهندسة', 'ja': 'エンジニアリング変換器',
    'zh-cn': '工程转换器', 'zh-tw': '工程轉換器', 'ru': 'Инженерные конвертеры', 'it': 'Convertitori per ingegneria', 'nl': 'Techniek omrekenen', 'tr': 'Mühendislik Dönüştürücüleri', 'ko': '공학 변환기', 'id': 'Konverter Teknik', 'vi': 'Bộ chuyển đổi kỹ thuật', 'th': 'เครื่องแปลงทางวิศวกรรม', 'pl': 'Konwerter inżynieryjny', 'uk': 'Інженерні конвертери', 'ro': 'Convertor inginerie', 'el': 'Μετατροπέας μηχανικής', 'sv': 'Ingenjörskonverterare', 'no': 'Ingeniørkonverterer', 'da': 'Ingeniøromregner', 'fi': 'Insinööriarvojen muunnin', 'cs': 'Inženýrské převodníky', 'hu': 'Mérnöki átváltók', 'he': 'ממיר הנדסי', 'ms': 'Penukar Kejuruteraan', 'bn': 'প্রকৌশল রূপান্তরকারী', 'ta': 'பொறியியல் மாற்றி', 'te': 'ఇంజనీరింగ్ మార్పిడి', 'mr': 'एन्जिनियरिंग कनवर्टर्स', 'gu': 'એન્જિનિયરિંગ કન્વર્ટર્સ', 'pa': 'ਇੰਜੀਨੀਅਰਿੰਗ ਕਨਵਰਟਰ', 'ur': 'انجینئرنگ کنورٹرز', 'fa': 'مبدل‌های مهندسی', 'tl': 'Tagasalin ng Pang-engineering'
  },
  'electrical': {
    'en': 'Electrical Converters', 'es': 'Conversor Eléctrico', 'hi': 'विद्युत कनवर्टर्स', 'fr': 'Convertisseurs Électriques', 'pt': 'Conversores Elétricos', 'de': 'Elektrische Umrechner', 'ar': 'المحولات الكهربائية', 'ja': '電気変換器',
    'zh-cn': '电气转换器', 'zh-tw': '電氣轉換器', 'ru': 'Электрические конвертеры', 'it': 'Convertitori elettrici', 'nl': 'Elektriciteit omrekenen', 'tr': 'Elektriksel Dönüştürücüler', 'ko': '전기 변환기', 'id': 'Konverter Listrik', 'vi': 'Bộ chuyển đổi điện', 'th': 'เครื่องแปลงไฟฟ้า', 'pl': 'Konwerter elektryczny', 'uk': 'Електричні конвертери', 'ro': 'Convertor electricitate', 'el': 'Μετατροπέας ηλεκτρικών μεγεθών', 'sv': 'Elektriska konverterare', 'no': 'Elektrisk konverterer', 'da': 'El-omregner', 'fi': 'Sähköarvojen muunnin', 'cs': 'Elektrické převodníky', 'hu': 'Elektromos átváltók', 'he': 'ממיר חשמלי', 'ms': 'Penukar Elektrik', 'bn': 'বৈদ্যুতিক রূপান্তরকারী', 'ta': 'மின்சார மாற்றி', 'te': 'విద్యుత్ మార్పిడి', 'mr': 'इलेक्ट्रिकल कनवर्टर', 'gu': 'ઇલેક્ટ્રિકલ કન્વર્ટર', 'pa': 'ਬਿਜਲੀ ਕਨਵਰਟਰ', 'ur': 'برقی کنورٹرز', 'fa': 'مبدل‌های الکتریکی', 'tl': 'Tagasalin ng Kuryente'
  },
  'miscellaneous': {
    'en': 'Miscellaneous Converters', 'es': 'Conversores Varios', 'hi': 'विविध कनवर्टर्स', 'fr': 'Convertisseurs Divers', 'pt': 'Conversores Diversos', 'de': 'Verschiedene Umrechner', 'ar': 'محولات متنوعة', 'ja': 'その他の変換器',
    'zh-cn': '杂项转换器', 'zh-tw': '雜項轉換器', 'ru': 'Разные конвертеры', 'it': 'Convertitori vari', 'nl': 'Diverse conversies', 'tr': 'Çeşitli Dönüştürücüler', 'ko': '기타 변환기', 'id': 'Konverter Serba-serbi', 'vi': 'Bộ chuyển đổi hỗn hợp', 'th': 'เครื่องแปลงทั่วไป', 'pl': 'Różne konwertery', 'uk': 'Різні конвертери', 'ro': 'Convertor diverse', 'el': 'Μετατροπέας διάφορων μεγεθών', 'sv': 'Diverse konverterare', 'no': 'Diverse konverterere', 'da': 'Diverse omregnere', 'fi': 'Sekalaiset muuntimet', 'cs': 'Různé převodníky', 'hu': 'Vegyes átváltók', 'he': 'ממירים שונים', 'ms': 'Penukar Pelbagai', 'bn': 'বিবিধ রূপান্তরকারী', 'ta': 'இதர மாற்றி', 'te': 'ఇతర మార్పిడులు', 'mr': 'विविध कनवर्टर', 'gu': 'વિવિધ કન્વર્ટર', 'pa': 'ਵੱਖ-ਵੱਖ ਕਨਵਰਟਰ', 'ur': 'متفرق کنورٹرز', 'fa': 'مبدل‌های متفرقه', 'tl': 'Iba pang Tagasalin'
  },

  // Calculators
  'percentage': {
    'en': 'Percentage Calculator', 'es': 'Calculadora de Porcentaje', 'hi': 'प्रतिशत कैलकुलेटर', 'fr': 'Calculatrice de Pourcentage', 'pt': 'Calculadora de Porcentagem', 'de': 'Prozentrechner', 'ar': 'حاسبة النسبة المئوية', 'ja': 'パーセント電卓',
    'zh-cn': '百分比计算器', 'zh-tw': '百分比計算器', 'ru': 'Калькулятор процентов', 'it': 'Calcolatore percentuale', 'nl': 'Procenten berekenen', 'tr': 'Yüzde Hesaplama', 'ko': '백분율 계산기', 'id': 'Kalkulator Persentase', 'vi': 'Máy tính phần trăm', 'th': 'เครื่องคำนวณเปอร์เซ็นต์', 'pl': 'Kalkulator procentowy', 'uk': 'Калькулятор відсотків', 'ro': 'Calculator procente', 'el': 'Υπολογισμός ποσοστού', 'sv': 'Procenträknare', 'no': 'Prosentkalkulator', 'da': 'Procentregner', 'fi': 'Prosenttilaskuri', 'cs': 'Procentní kalkulačka', 'hu': 'Százalékkalkulátor', 'he': 'מחשבון אחוזים', 'ms': 'Kalkulator Peratusan', 'bn': 'শতকরা ক্যালকুলেটর', 'ta': 'சதவீத கால்குலேட்டர்', 'te': 'శాతం కాల్కులేటర్', 'mr': 'ટકાવારી કેલ્ક્યુલેટર', 'gu': 'ટકાવારી કેલ્ક્યુલેટર', 'pa': 'ਪ੍ਰਤੀਸ਼ਤ ਕੈਲਕੁਲੇਟਰ', 'ur': 'فیصد کیلکولیٹر', 'fa': 'ماشین حساب درصد', 'tl': 'Kalkulator ng Porsyento'
  },
  'bmi': {
    'en': 'BMI Calculator', 'es': 'Calculadora de IMC', 'hi': 'बीएमआई कैलकुलेटर', 'fr': "Calculatrice d'IMC", 'pt': 'Calculadora de IMC', 'de': 'BMI-Rechner', 'ar': 'حاسبة مؤشر كتلة الجسم', 'ja': 'BMI電卓',
    'zh-cn': 'BMI计算器', 'zh-tw': 'BMI計算器', 'ru': 'Калькулятор ИМТ', 'it': 'Calcolo IMC', 'nl': 'BMI berekenen', 'tr': 'BMI Hesaplama', 'ko': 'BMI 계산기', 'id': 'Kalkulator BMI', 'vi': 'Máy tính BMI', 'th': 'เครื่องคำนวณ BMI', 'pl': 'Kalkulator BMI', 'uk': 'Калькулятор ІМТ', 'ro': 'Calculator IMC', 'el': 'Υπολογισμός ΔΜΣ', 'sv': 'BMI-räknare', 'no': 'BMI-kalkulator', 'da': 'BMI-beregner', 'fi': 'Painoindeksilaskuri', 'cs': 'BMI kalkulačka', 'hu': 'BMI kalkulátor', 'he': 'מחשבון BMI', 'ms': 'Kalkulator BMI', 'bn': 'বিএমআই ক্যালকুলেটর', 'ta': 'பிஎம்ஐ கால்குலேட்டர்', 'te': 'బీఎంఐ కాల్కులేటర్', 'mr': 'BMI કેલ્ક્યુલેટર', 'gu': 'BMI કેલ્ક્યુલેટર', 'pa': 'BMI ਕੈਲਕੁਲੇਟਰ', 'ur': 'بی ایم آئی کیلکولیٹر', 'fa': 'ماشین حساب شاخص توده بدنی', 'tl': 'Kalkulator ng BMI'
  },
  'bmr': {
    'en': 'BMR Calculator', 'es': 'Calculadora de TMB', 'hi': 'बीएमआर कैलकुलेटर', 'fr': 'Calculatrice de TMB', 'pt': 'Calculadora de TMB', 'de': 'BMR-Rechner', 'ar': 'حاسبة معدل الأيض الأساسي', 'ja': 'BMR電卓',
    'zh-cn': 'BMR计算器', 'zh-tw': 'BMR計算器', 'ru': 'Калькулятор BMR', 'it': 'Calcolo BMR', 'nl': 'BMR berekenen', 'tr': 'BMR Hesaplama', 'ko': 'BMR 계산기', 'id': 'Kalkulator BMR', 'vi': 'Máy tính BMR', 'th': 'เครื่องคำนวณ BMR', 'pl': 'Kalkulator BMR', 'uk': 'Калькулятор BMR', 'ro': 'Calculator BMR', 'el': 'Υπολογισμός BMR', 'sv': 'BMR-räknare', 'no': 'BMR-kalkulator', 'da': 'BMR-beregner', 'fi': 'Perusaineenvaihduntalaskuri', 'cs': 'BMR kalkulačka', 'hu': 'BMR kalkulátor', 'he': 'מחשבון BMR', 'ms': 'Kalkulator BMR', 'bn': 'বিএমআর ক্যালকুলেটর', 'ta': 'பிஎம்ஆர் கால்குலேட்டர்', 'te': 'బీఎమ్ఆర్ కాల్కులేటర్', 'mr': 'BMR કેલ્ક્યુલેટર', 'gu': 'BMR કેલ્ક્યુલેટર', 'pa': 'BMR ਕੈਲਕੁਲੇਟਰ', 'ur': 'بی ایم آر کیلکولیٹر', 'fa': 'ماشین حساب نرخ متابولیسم پایه', 'tl': 'Kalkulator ng BMR'
  },
  'calorie': {
    'en': 'Calorie Calculator', 'es': 'Calculadora de Calorías', 'hi': 'कैलोरी कैलकुलेटर', 'fr': 'Calculatrice de Calories', 'pt': 'Calculadora de Calorias', 'de': 'Kalorienrechner', 'ar': 'حاسبة السعرات الحرارية', 'ja': 'カロリー電卓',
    'zh-cn': '卡路里计算器', 'zh-tw': '卡路里計算器', 'ru': 'Калькулятор калорий', 'it': 'Contatore calorie', 'nl': 'Calorieën berekenen', 'tr': 'Kalori Hesaplama', 'ko': '칼로리 계산기', 'id': 'Kalkulator Kalori', 'vi': 'Máy tính calo', 'th': 'เครื่องคำนวณแคลอรี่', 'pl': 'Kalkulator kalorii', 'uk': 'Калькулятор калорій', 'ro': 'Calculator calorii', 'el': 'Υπολογισμός θερμίδων', 'sv': 'Kaloriräknare', 'no': 'Kalorikalkulator', 'da': 'Kalorieberegner', 'fi': 'Kalorilaskuri', 'cs': 'Kalorická kalkulačka', 'hu': 'Kalóriakalkulátor', 'he': 'מחשבון קלוריות', 'ms': 'Kalkulator Kalori', 'bn': 'ক্যালোরি ক্যালকুলেটর', 'ta': 'கலோரி கால்குலேட்டர்', 'te': 'క్యాలరీ కాల్కులేటర్', 'mr': 'કેલરી કેલ્ક્યુલેટર', 'gu': 'કેલરી કેલ્ક્યુલેટર', 'pa': 'ਕੈਲੋਰੀ ਕੈਲਕੁਲੇਟਰ', 'ur': 'کیلوری کیلکولیٹر', 'fa': 'ماشین حساب کالری', 'tl': 'Kalkulator ng Calorie'
  },
  'age': {
    'en': 'Age Calculator', 'es': 'Calculadora de Edad', 'hi': 'आयु कैलकुलेटर', 'fr': "Calculatrice d'Âge", 'pt': 'Calculadora de Idade', 'de': 'Alter-Rechner', 'ar': 'حاسبة العمر', 'ja': '年齢電卓',
    'zh-cn': '年龄计算器', 'zh-tw': '年齡計算器', 'ru': 'Калькулятор возраста', 'it': 'Calcolo età', 'nl': 'Leeftijd berekenen', 'tr': 'Yaş Hesaplama', 'ko': '나이 계산기', 'id': 'Kalkulator Umur', 'vi': 'Máy tính tuổi', 'th': 'เครื่องคำนวณอายุ', 'pl': 'Kalkulator wieku', 'uk': 'Калькулятор віку', 'ro': 'Calculator vârstă', 'el': 'Υπολογισμός ηλικίας', 'sv': 'Åldersräknare', 'no': 'Alderskalkulator', 'da': 'Aldersberegner', 'fi': 'Ikälaskuri', 'cs': 'Věková kalkulačka', 'hu': 'Korkalkulátor', 'he': 'מחשבון גיל', 'ms': 'Kalkulator Umur', 'bn': 'বয়স ক্যালকুলেটর', 'ta': 'வயது கால்குலேட்டர்', 'te': 'వయస్సు కాల్కులేటర్', 'mr': 'ઉંમર કેલ્ક્યુલેટર', 'gu': 'ઉંમર કેલ્ક્યુલેટર', 'pa': 'ਉਮਰ ਕੈਲਕੁਲੇਟਰ', 'ur': 'عمر کا کیلکولیٹر', 'fa': 'ماشین حساب سن', 'tl': 'Kalkulator ng Edad'
  },
  'gpa': {
    'en': 'GPA Calculator', 'es': 'Calculadora de GPA', 'hi': 'जीपीए कैलकुलेटर', 'fr': 'Calculatrice de GPA', 'pt': 'Calculadora de GPA', 'de': 'GPA-Rechner', 'ar': 'حاسبة المعدل التراكمي', 'ja': 'GPA電卓',
    'zh-cn': 'GPA计算器', 'zh-tw': 'GPA計算器', 'ru': 'Калькулятор GPA', 'it': 'Calcolo media voti', 'nl': 'GPA berekenen', 'tr': 'GPA Hesaplama', 'ko': 'GPA 계산기', 'id': 'Kalkulator GPA', 'vi': 'Máy tính điểm GPA', 'th': 'เครื่องคำนวณเกรดเฉลี่ย', 'pl': 'Kalkulator GPA', 'uk': 'Калькулятор GPA', 'ro': 'Calculator GPA', 'el': 'Υπολογισμός GPA', 'sv': 'GPA-räknare', 'no': 'GPA-kalkulator', 'da': 'GPA-beregner', 'fi': 'Keskiarvolaskuri', 'cs': 'GPA kalkulačka', 'hu': 'GPA kalkulátor', 'he': 'מחשבון ממוצע ציונים', 'ms': 'Kalkulator GPA', 'bn': 'জিপিএ ক্যালকুলেটর', 'ta': 'ஜிபிஏ கால்குலேட்டர்', 'te': 'జీపీఏ కాల్కులేటర్', 'mr': 'GPA કેલ્ક્યુલેટર', 'gu': 'GPA કેલ્ક્યુલેટર', 'pa': 'GPA ਕੈਲਕੁਲੇਟਰ', 'ur': 'جی پی اے کیلکولیٹر', 'fa': 'ماشین حساب معدل', 'tl': 'Kalkulator ng GPA'
  },
  'discount': {
    'en': 'Discount Calculator', 'es': 'Calculadora de Descuentos', 'hi': 'छूट कैलकुलेटर', 'fr': 'Calculatrice de Remise', 'pt': 'Calculadora de Desconto', 'de': 'Rabattrechner', 'ar': 'حاسبة الخصم', 'ja': '割引電卓',
    'zh-cn': '折扣计算器', 'zh-tw': '折扣計算器', 'ru': 'Калькулятор скидок', 'it': 'Calcolo sconto', 'nl': 'Korting berekenen', 'tr': 'İndirim Hesaplama', 'ko': '할인 계산기', 'id': 'Kalkulator Diskon', 'vi': 'Máy tính giảm giá', 'th': 'เครื่องคำนวณส่วนลด', 'pl': 'Kalkulator rabatów', 'uk': 'Калькулятор знижок', 'ro': 'Calculator reduceri', 'el': 'Υπολογισμός έκπτωσης', 'sv': 'Rabatträknare', 'no': 'Rabattkalkulator', 'da': 'Rabatberegner', 'fi': 'Alennuslaskuri', 'cs': 'Slevová kalkulačka', 'hu': 'Kedvezménykalkulátor', 'he': 'מחשבון הנחות', 'ms': 'Kalkulator Diskon', 'bn': 'ডিসকাউন্ট ক্যালকুলেটর', 'ta': 'தள்ளுபடி கால்குலேட்டர்', 'te': 'డిస్కౌంట్ కాల్కులేటర్', 'mr': 'ડિસ્કાઉન્ટ કેલ્ક્યુલેટર', 'gu': 'ડિસ્કાઉન્ટ કેલ્ક્યુલેટર', 'pa': 'ਡਿਸਕਾਉਂਟ ਕੈਲਕੁਲੇਟਰ', 'ur': 'ڈسکاؤنٹ کیلکولیٹر', 'fa': 'ماشین حساب تخفیف', 'tl': 'Kalkulator ng Diskuwento'
  },
  'loan': {
    'en': 'Loan Calculator', 'es': 'Calculadora de Préstamos', 'hi': 'ऋण कैलकुलेटर', 'fr': 'Calculatrice de Prêt', 'pt': 'Calculadora de Empréstimo', 'de': 'Kreditrechner', 'ar': 'حاسبة القروض', 'ja': 'ローン電卓',
    'zh-cn': '贷款计算器', 'zh-tw': '貸款計算器', 'ru': 'Кредитный калькулятор', 'it': 'Calcolatore mutuo', 'nl': 'Lening berekenen', 'tr': 'Kredi Hesaplama', 'ko': '대출 계산기', 'id': 'Kalkulator Pinjaman', 'vi': 'Máy tính khoản vay', 'th': 'เครื่องคำนวณเงินกู้', 'pl': 'Kalkulator kredytowy', 'uk': 'Кредитний калькулятор', 'ro': 'Calculator împrumut', 'el': 'Υπολογισμός δανείου', 'sv': 'Låneräknare', 'no': 'Lånekalkulator', 'da': 'Låneberegner', 'fi': 'Lainalaskuri', 'cs': 'Půjčková kalkulačka', 'hu': 'Hitelkalkulátor', 'he': 'מחשבון הלוואות', 'ms': 'Kalkulator Pinjaman', 'bn': 'ঋণ ক্যালকুলেটর', 'ta': 'கடன் கால்குலேட்டர்', 'te': 'రుణ కాల్కులేటర్', 'mr': 'લોન કેલ્ક્યુલેટર', 'gu': 'લોન કેલ્ક્યુલેટર', 'pa': 'ਲੋਨ ਕੈਲਕੁਲੇਟਰ', 'ur': 'لون کیلکولیٹر', 'fa': 'ماشین حساب وام', 'tl': 'Kalkulator ng Utang'
  },
  'emi': {
    'en': 'EMI Calculator', 'es': 'Calculadora de EMI', 'hi': 'ईएमआई कैलकुलेटर', 'fr': "Calculatrice d'EMI", 'pt': 'Calculadora de EMI', 'de': 'EMI-Rechner', 'ar': 'حاسبة الأقساط الشهرية', 'ja': 'EMI電卓',
    'zh-cn': 'EMI计算器', 'zh-tw': 'EMI計算器', 'ru': 'Калькулятор EMI', 'it': 'Calcolo EMI', 'nl': 'EMI berekenen', 'tr': 'EMI Hesaplama', 'ko': 'EMI 계산기', 'id': 'Kalkulator EMI', 'vi': 'Máy tính trả góp EMI', 'th': 'เครื่องคำนวณ EMI', 'pl': 'Kalkulator EMI', 'uk': 'Калькулятор EMI', 'ro': 'Calculator EMI', 'el': 'Υπολογισμός EMI', 'sv': 'EMI-räknare', 'no': 'EMI-kalkulator', 'da': 'EMI-beregner', 'fi': 'EMI-laskuri', 'cs': 'EMI kalkulačka', 'hu': 'EMI kalkulátor', 'he': 'מחשבון EMI', 'ms': 'Kalkulator EMI', 'bn': 'ইএমআই ক্যালকুলেটর', 'ta': 'இஎம்ஐ கால்குலேட்டர்', 'te': 'ఈఎంఐ కాల్కులేటర్', 'mr': 'EMI કેલ્ક્યુલેટર', 'gu': 'EMI કેલ્ક્યુલેટર', 'pa': 'EMI ਕੈਲਕੁਲੇਟਰ', 'ur': 'ای ایم آئی کیلکولیٹر', 'fa': 'ماشین حساب قسط ماهانه', 'tl': 'Kalkulator ng EMI'
  },
  'scientific': {
    'en': 'Scientific Calculator', 'es': 'Calculadora Científica', 'hi': 'वैज्ञानिक कैलकुलेटर', 'fr': 'Calculatrice Scientifique', 'pt': 'Calculadora Científica', 'de': 'Wissenschaftlicher Rechner', 'ar': 'الحاسبة العلمية', 'ja': '科学電卓',
    'zh-cn': '科学计算器', 'zh-tw': '科學計算器', 'ru': 'Научный калькулятор', 'it': 'Calcolatrice scientifica', 'nl': 'Wetenschappelijke rekenmachine', 'tr': 'Bilimsel Hesap Makinesi', 'ko': '공학용 계산기', 'id': 'Kalkulator Ilmiah', 'vi': 'Máy tính khoa học', 'th': 'เครื่องคิดเลขวิทยาศาสตร์', 'pl': 'Kalkulator naukowy', 'uk': 'Науковий калькулятор', 'ro': 'Calculator științific', 'el': 'Επιστημονική αριθμομηχανή', 'sv': 'Vetenskaplig räknare', 'no': 'Vitenskapelig kalkulator', 'da': 'Videnskabelig lommeregner', 'fi': 'Funktiolaskuri', 'cs': 'Vědecká kalkulačka', 'hu': 'Tudományos számológép', 'he': 'מחשבון מדעי', 'ms': 'Kalkulator Saintifik', 'bn': 'বৈজ্ঞানিক ক্যালকুলেটর', 'ta': 'அறிவியல் கால்குலேட்டர்', 'te': 'శాస్త్రీయ కాల్కులేటర్', 'mr': 'વૈજ્ઞાનિક કેલ્ક્યુલેટર', 'gu': 'વૈજ્ઞાનિક કેલ્ક્યુલેટર', 'pa': 'ਵਿਗਿਆਨਕ ਕੈਲਕੁਲੇਟਰ', 'ur': 'سائنسی کیلکولیٹر', 'fa': 'ماشین حساب علمی', 'tl': 'Kalkulator na Pang-agham'
  },
  'interest': {
    'en': 'Interest Calculator', 'es': 'Calculadora de Interés', 'hi': 'ब्याज कैलकुलेटर', 'fr': "Calculatrice d'Intérêts", 'pt': 'Calculadora de Juros', 'de': 'Zinsrechner', 'ar': 'حاسبة الفائدة', 'ja': '金利電卓',
    'zh-cn': '利息计算器', 'zh-tw': '利息計算器', 'ru': 'Калькулятор процентов', 'it': 'Calcolo interessi', 'nl': 'Renteberekening', 'tr': 'Faiz Hesaplama', 'ko': '이자 계산기', 'id': 'Kalkulator Bunga', 'vi': 'Máy tính lãi suất', 'th': 'เครื่องคำนวณดอกเบี้ย', 'pl': 'Kalkulator odsetkowy', 'uk': 'Калькулятор відсотків', 'ro': 'Calculator dobândă', 'el': 'Υπολογισμός τόκων', 'sv': 'Ränteräknare', 'no': 'Rentekalkulator', 'da': 'Renteberegner', 'fi': 'Korkolaskuri', 'cs': 'Úroková kalkulačka', 'hu': 'Kamatkalkulátor', 'he': 'מחשבון ריבית', 'ms': 'Kalkulator Faedah', 'bn': 'সুদ ক্যালকুলেটর', 'ta': 'வட்டி கால்குலேட்டர்', 'te': 'వడ్డీ కాల్కులేటర్', 'mr': 'વ્યાજ કેલ્ક્યુલેટર', 'gu': 'વ્યાજ કેલ્ક્યુલેટર', 'pa': 'ਵਿਆਜ ਕੈਲਕੁਲੇਟਰ', 'ur': 'سود کا کیلکولیٹر', 'fa': 'ماشین حساب بهره', 'tl': 'Kalkulator ng Interes'
  },
  'simple-interest': {
    'en': 'Simple Interest Calculator', 'es': 'Calculadora de Interés Simple', 'hi': 'साधारण ब्याज कैलकुलेटर', 'fr': 'Intérêt Simple', 'pt': 'Juros Simples', 'de': 'Einfacher Zinsrechner', 'ar': 'حاسبة الفائدة البسيطة', 'ja': '単利電卓',
    'zh-cn': '单利计算器', 'zh-tw': '單利計算器', 'ru': 'Простые проценты', 'it': 'Interesse semplice', 'nl': 'Enkelvoudige rente', 'tr': 'Basit Faiz Hesaplama', 'ko': '단리 계산기', 'id': 'Kalkulator Bunga Tunggal', 'vi': 'Máy tính lãi đơn', 'th': 'เครื่องคำนวณดอกเบี้ยอย่างง่าย', 'pl': 'Kalkulator odsetek prostych', 'uk': 'Прості відсотки', 'ro': 'Calculator dobândă simplă', 'el': 'Υπολογισμός απλού τόκου', 'sv': 'Enkel ränteräknare', 'no': 'Enkel rentekalkulator', 'da': 'Simpel renteberegner', 'fi': 'Yksinkertainen korkolaskuri', 'cs': 'Kalkulačka jednoduchého úroku', 'hu': 'Egyszerű kamatozás-kalkulátor', 'he': 'מחשבון ריבית פשוטה', 'ms': 'Kalkulator Faedah Mudah', 'bn': 'সরল সুদ ক্যালকুলেটর', 'ta': 'தனிவட்டி கால்குலேட்டர்', 'te': 'సాధారణ వడ్డీ కాల్కులేటర్', 'mr': 'साधारण વ્યાજ કેલ્ક્યુલેટર', 'gu': 'સાદું વ્યાજ કેલ્ક્યુલેટર', 'pa': 'ਸਾਧਾਰਨ ਵਿਆਜ ਕੈਲਕੁਲੇਟਰ', 'ur': 'سادہ سود کیلکولیٹر', 'fa': 'ماشین حساب بهره ساده', 'tl': 'Kalkulator ng Simple Interest'
  },
  'compound-interest': {
    'en': 'Compound Interest Calculator', 'es': 'Calculadora de Interés Compuesto', 'hi': 'चक्रवृद्धि ब्याज कैलकुलेटर', 'fr': 'Intérêt Composé', 'pt': 'Juros Compostos', 'de': 'Zinseszinsrechner', 'ar': 'حاسبة الفائدة المركبة', 'ja': '複利電卓',
    'zh-cn': '复利计算器', 'zh-tw': '複利計算器', 'ru': 'Сложные проценты', 'it': 'Interesse composto', 'nl': 'Samengestelde rente', 'tr': 'Bileşik Faiz Hesaplama', 'ko': '복리 계산기', 'id': 'Kalkulator Bunga Majemuk', 'vi': 'Máy tính lãi kép', 'th': 'เครื่องคำนวณดอกเบี้ยทบต้น', 'pl': 'Kalkulator odsetek składanych', 'uk': 'Складні відсотки', 'ro': 'Calculator dobândă compusă', 'el': 'Υπολογισμός σύνθετου τόκου', 'sv': 'Ränte-på-ränte-räknare', 'no': 'Renters rente-kalkulator', 'da': 'Renters rente-beregner', 'fi': 'Korkoa korolle -laskuri', 'cs': 'Kalkulačka složeného úroku', 'hu': 'Kamatoskamat-kalkulátor', 'he': 'מחשבון ריבית דריבית', 'ms': 'Kalkulator Faedah Kompaun', 'bn': 'চক্রবৃদ্ধি সুদ ক্যালকুলেটর', 'ta': 'கூட்டுவட்டி கால்குலேட்டர்', 'te': 'చక్రవడ్డీ కాల్కులేటర్', 'mr': 'ચક્રવૃદ્ધિ વ્યાજ કેલ્ક્યુલેટર', 'gu': 'ચક્રવૃદ્ધિ વ્યાજ કેલ્ક્યુલેટર', 'pa': 'ਚੱਕਰਵਰਤੀ ਵਿਆਜ ਕੈਲਕੁਲੇਟਰ', 'ur': 'مرکب سود کیلکولیٹر', 'fa': 'ماشین حساب بهره مرکب', 'tl': 'Kalkulator ng Compound Interest'
  },
  'gst': {
    'en': 'GST Calculator', 'es': 'Calculadora de GST', 'hi': 'जीएसटी कैलकुलेटर', 'fr': 'Calculatrice de GST', 'pt': 'Calculadora de GST', 'de': 'GST-Rechner', 'ar': 'حاسبة ضريبة السلع والخدمات', 'ja': 'GST電卓',
    'zh-cn': 'GST计算器', 'zh-tw': 'GST計算器', 'ru': 'Калькулятор GST', 'it': 'Calcolo GST', 'nl': 'GST berekenen', 'tr': 'GST Hesaplama', 'ko': 'GST 계산기', 'id': 'Kalkulator GST', 'vi': 'Máy tính thuế GST', 'th': 'เครื่องคำนวณ GST', 'pl': 'Kalkulator GST', 'uk': 'Калькулятор GST', 'ro': 'Calculator GST', 'el': 'Υπολογισμός GST', 'sv': 'GST-räknare', 'no': 'GST-kalkulator', 'da': 'GST-beregner', 'fi': 'GST-laskuri', 'cs': 'GST kalkulačka', 'hu': 'GST kalkulátor', 'he': 'מחשבון GST', 'ms': 'Kalkulator GST', 'bn': 'জিএসটি ক্যালকুলেটর', 'ta': 'ஜிஎஸ்டி கால்குலேட்டர்', 'te': 'జీఎస్టీ కాల్కులేటర్', 'mr': 'GST કેલ્ક્યુલેટર', 'gu': 'GST કેલ્ક્યુલેટર', 'pa': 'GST ਕੈਲਕੁਲੇਟਰ', 'ur': 'جی ایس ٹی کیلکولیٹر', 'fa': 'ماشین حساب مالیات بر کالا و خدمات', 'tl': 'Kalkulator ng GST'
  },
  'marks-percentage': {
    'en': 'Marks Percentage Calculator', 'es': 'Porcentaje de Notas', 'hi': 'अंक प्रतिशत कैलकुलेटर', 'fr': 'Pourcentage de Notes', 'pt': 'Porcentagem de Notas', 'de': 'Notenprozentrechner', 'ar': 'حاسبة نسبة الدرجات', 'ja': '成績割合電卓',
    'zh-cn': '成绩百分比计算器', 'zh-tw': '成績百分比計算器', 'ru': 'Проценты оценок', 'it': 'Percentuale voti', 'nl': 'Cijferpercentage berekenen', 'tr': 'Not Yüzdesi Hesaplama', 'ko': '성적 백분율 계산기', 'id': 'Kalkulator Persentase Nilai', 'vi': 'Máy tính phần trăm điểm', 'th': 'เครื่องคำนวณเปอร์เซ็นต์คะแนน', 'pl': 'Kalkulator procentu ocen', 'uk': 'Калькулятор відсотків оцінок', 'ro': 'Calculator procente note', 'el': 'Υπολογισμός ποσοστού βαθμολογίας', 'sv': 'Betygsprocenträknare', 'no': 'Karakterprosentkalkulator', 'da': 'Karakterprocentregner', 'fi': 'Arvosanaprosenttilaskuri', 'cs': 'Kalkulačka procent známek', 'hu': 'Osztályzat-százalék kalkulátor', 'he': 'מחשבון אחוז ציונים', 'ms': 'Kalkulator Peratusan Markah', 'bn': 'নম্বর শতকরা ক্যালকুলেটর', 'ta': 'மதிப்பெண் சதவீத கால்குலேட்டர்', 'te': 'మార్కుల శాతం కాల్కులేటర్', 'mr': 'गुण टक्केवारी कॅल्क्युलेटर', 'gu': 'ગુણ ટકાવારી કેલ્ક્યુલેટર', 'pa': 'ਅੰਕਾਂ ਦੀ ਪ੍ਰਤੀਸ਼ਤਤਾ ਕੈਲਕੁਲੇਟਰ', 'ur': 'نمبروں کا فیصد کیلکولیٹر', 'fa': 'ماشین حساب درصد نمرات', 'tl': 'Kalkulator ng Porsyento ng Marka'
  },
  'date-difference': {
    'en': 'Date Difference Calculator', 'es': 'Diferencia de Fechas', 'hi': 'तिथि अंतर कैलकुलेटर', 'fr': 'Différence de Dates', 'pt': 'Diferença de Datas', 'de': 'Datum-Differenz-Rechner', 'ar': 'حاسبة فرق التاريخ', 'ja': '日付差電卓',
    'zh-cn': '日期差计算器', 'zh-tw': '日期差計算器', 'ru': 'Разница дат', 'it': 'Differenza date', 'nl': 'Datumverschil berekenen', 'tr': 'Tarih Farkı Hesaplama', 'ko': '날짜 차이 계산기', 'id': 'Kalkulator Selisih Tanggal', 'vi': 'Máy tính khoảng cách ngày', 'th': 'เครื่องคำนวณส่วนต่างวันที่', 'pl': 'Kalkulator różnicy dat', 'uk': 'Калькулятор різниці дат', 'ro': 'Calculator diferență date', 'el': 'Υπολογισμός διαφοράς ημερομηνιών', 'sv': 'Datumdifferensräknare', 'no': 'Datodifferanskalkulator', 'da': 'Datodifferensberegner', 'fi': 'Päivämääräerolaskuri', 'cs': 'Kalkulačka rozdílu dat', 'hu': 'Dátumkülönbség-kalkulátor', 'he': 'מחשבון הפרש תאריכים', 'ms': 'Kalkulator Perbezaan Tarikh', 'bn': 'তারিখের পার্থক্য ক্যালকুলেটর', 'ta': 'தேதி வேறுபாடு கால்குலேட்டர்', 'te': 'తేదీల వ్యత్యాసం కాల్కులేటర్', 'mr': 'તારીખ તફાવત કેલ્ક્યુલેટર', 'gu': 'તારીખ તફાવત કેલ્ક્યુલેટર', 'pa': 'ਤਾਰੀਖਾਂ ਦਾ ਅੰਤਰ ਕੈਲਕੁਲੇਟਰ', 'ur': 'تاریخوں کا فرق کیلکولیٹر', 'fa': 'ماشین حساب اختلاف تاریخ', 'tl': 'Kalkulator ng Pagkakaiba ng Petsa'
  },
  'time-duration': {
    'en': 'Time Duration Calculator', 'es': 'Duración de Tiempo', 'hi': 'समय अवधि कैलकुलेटर', 'fr': 'Durée de Temps', 'pt': 'Duração de Tempo', 'de': 'Zeitdauer-Rechner', 'ar': 'حاسبة مدة الوقت', 'ja': '期間電卓',
    'zh-cn': '时长计算器', 'zh-tw': '時長計算器', 'ru': 'Продолжительность времени', 'it': 'Durata tempo', 'nl': 'Tijdsduur berekenen', 'tr': 'Zaman Süresi Hesaplama', 'ko': '시간 경과 계산기', 'id': 'Kalkulator Durasi Waktu', 'vi': 'Máy tính thời lượng', 'th': 'เครื่องคำนวณระยะเวลา', 'pl': 'Kalkulator czasu trwania', 'uk': 'Калькулятор тривалості часу', 'ro': 'Calculator durată timp', 'el': 'Υπολογισμός χρονικής διάρκειας', 'sv': 'Tidslängdsräknare', 'no': 'Tidsvarighetskalkulator', 'da': 'Tidsvarighedsberegner', 'fi': 'Ajan kestolaskuri', 'cs': 'Kalkulačka doby trvání', 'hu': 'Időtartam-kalkulátor', 'he': 'מחשבון משך זמן', 'ms': 'Kalkulator Durasi Masa', 'bn': 'সময়কাল ক্যালকুলেটর', 'ta': 'நேர கால அளவு கால்குலேட்டர்', 'te': 'సమయ వ్యవధి కాల్కులేటర్', 'mr': 'સમય ગાળો કેલ્ક્યુલેટર', 'gu': 'સમય ગાળો કેલ્ક્યુલેટર', 'pa': 'ਸਮਾਂ ਅਵਧੀ ਕੈਲਕੁਲੇਟਰ', 'ur': 'وقت کا دورانیہ کیلکولیٹر', 'fa': 'ماشین حساب مدت زمان', 'tl': 'Kalkulator ng Tagal ng Oras'
  },
  'average': {
    'en': 'Average Calculator', 'es': 'Calculadora de Promedio', 'hi': 'औसत कैलकुलेटर', 'fr': 'Calculatrice de Moyenne', 'pt': 'Calculadora de Média', 'de': 'Mittelwertrechner', 'ar': 'حاسبة المتوسط', 'ja': '平均電卓',
    'zh-cn': '平均值计算器', 'zh-tw': '平均值計算器', 'ru': 'Калькулятор среднего значения', 'it': 'Calcolo media', 'nl': 'Gemiddelde berekenen', 'tr': 'Ortalama Hesaplama', 'ko': '평균 계산기', 'id': 'Kalkulator Rata-rata', 'vi': 'Máy tính trung bình', 'th': 'เครื่องคำนวณค่าเฉลี่ย', 'pl': 'Kalkulator średniej', 'uk': 'Калькулятор середнього значення', 'ro': 'Calculator medie', 'el': 'Υπολογισμός μέσου όρου', 'sv': 'Medelvärdesräknare', 'no': 'Gjennomsnittskalkulator', 'da': 'Gennemsnitsberegner', 'fi': 'Keskiarvolaskuri', 'cs': 'Kalkulačka průměru', 'hu': 'Átlagkalkulátor', 'he': 'מחשבון ממוצע', 'ms': 'Kalkulator Purata', 'bn': 'গড় ক্যালকুলেটর', 'ta': 'சராசரி கால்குலேட்டர்', 'te': 'సగటు కాల్కులేటర్', 'mr': 'સરેરાશ કેલ્ક્યુલેટર', 'gu': 'સરેરાશ કેલ્ક્યુલેટર', 'pa': 'ਔਸਤ ਕੈਲਕੁਲੇਟਰ', 'ur': 'اوسط کیلکولیٹر', 'fa': 'ماشین حساب میانگین', 'tl': 'Kalkulator ng Average'
  },

  // Scientific Tools
  'scientific-notation': {
    'en': 'Scientific Notation Converter', 'es': 'Notación Científica', 'hi': 'वैज्ञानिक संकेत कनवर्टर', 'fr': 'Notation Scientifique', 'pt': 'Notação Científica', 'de': 'Wissenschaftliche Schreibweise', 'ar': 'محول الكسر العلمي', 'ja': '科学的表記変換器',
    'zh-cn': '科学记数法转换器', 'zh-tw': '科學記數法轉換器', 'ru': 'Научная нотация', 'it': 'Notazione scientifica', 'nl': 'Wetenschappelijke notatie', 'tr': 'Bilimsel Gösterim Dönüştürücü', 'ko': '과학적 표기법 변환기', 'id': 'Konverter Notasi Ilmiah', 'vi': 'Bộ chuyển đổi ký hiệu khoa học', 'th': 'เครื่องแปลงสัญลักษณ์วิทยาศาสตร์', 'pl': 'Konwerter zapisu naukowego', 'uk': 'Наукова нотація', 'ro': 'Convertor notație științifică', 'el': 'Μετατροπέας επιστημονικής σημειογραφίας', 'sv': 'Grundpotensformskonverterare', 'no': 'Vitenskapelig notasjon-konverterer', 'da': 'Videnskabelig notation-omregner', 'fi': 'Kymmenpotenssimuunnin', 'cs': 'Převodník vědeckého zápisu', 'hu': 'Tudományos alak átváltó', 'he': 'ממיר כתיב מדעי', 'ms': 'Penukar Notasi Saintifik', 'bn': 'বৈজ্ঞানিক নোটেশন রূপান্তরকারী', 'ta': 'அறிவியல் குறியீடு மாற்றி', 'te': 'శాస్త్రీయ సంకేత మార్పిడి', 'mr': 'વૈજ્ઞાનિક સંકેત કન્વર્ટર', 'gu': 'વૈજ્ઞાનિક સંકેત કન્વર્ટર', 'pa': 'ਵਿਗਿਆਨਕ ਸੰਕੇਤ ਕਨਵਰਟਰ', 'ur': 'سائنسی نوٹیشن کنورٹر', 'fa': 'مبدل نماد علمی', 'tl': 'Tagasalin ng Scientific Notation'
  },
  'number-base': {
    'en': 'Number Base Converter', 'es': 'Base Numérica', 'hi': 'संख्या आधार कनवर्टर', 'fr': 'Base Numérique', 'pt': 'Base Numérica', 'de': 'Zahlenbasis-Umrechner', 'ar': 'محول أساس الأعداد', 'ja': '基数変換器',
    'zh-cn': '数制转换器', 'zh-tw': '數制轉換器', 'ru': 'Системы счисления', 'it': 'Base numerica', 'nl': 'Talstelsel omrekenen', 'tr': 'Sayı Tabanı Dönüştürücü', 'ko': '진법 변환기', 'id': 'Konverter Basis Bilangan', 'vi': 'Bộ chuyển đổi cơ số', 'th': 'เครื่องแปลงฐานเลข', 'pl': 'Konwerter baz liczbowych', 'uk': 'Конвертер систем числення', 'ro': 'Convertor baze numerice', 'el': 'Μετατροπέας βάσης αριθμών', 'sv': 'Basomvandlare', 'no': 'Tallbasiskonverterer', 'da': 'Talsystemsomregner', 'fi': 'Lukujärjestelmämuunnin', 'cs': 'Převodník číselných soustav', 'hu': 'Számrendszer átváltó', 'he': 'ממיר בסיסי מספרים', 'ms': 'Penukar Asas Nombor', 'bn': 'সংখ্যা ভিত্তি রূপান্তরকারী', 'ta': 'எண் அடிப்படை மாற்றி', 'te': 'సంఖ్యా ఆధార మార్పిడి', 'mr': 'नંબર બેઝ કન્વર્ટર', 'gu': 'નંબર બેઝ કન્વર્ટર', 'pa': 'ਸੰਖਿਆ ਅਧਾਰ ਕਨਵਰਟਰ', 'ur': 'نمبر بیس کنورٹر', 'fa': 'مبدل مبنای عدد', 'tl': 'Tagasalin ng Base ng Numero'
  },
  'fraction': {
    'en': 'Fraction Calculator', 'es': 'Calculadora de Fracciones', 'hi': 'भिन्न कैलकुलेटर', 'fr': 'Calculatrice de Fractions', 'pt': 'Calculadora de Frações', 'de': 'Bruchrechner', 'ar': 'حاسبة الكسور', 'ja': '分数電卓',
    'zh-cn': '分数计算器', 'zh-tw': '分數計算器', 'ru': 'Калькулятор дробей', 'it': 'Calcolo frazioni', 'nl': 'Breuken berekenen', 'tr': 'Kesir Hesaplama', 'ko': '분수 계산기', 'id': 'Kalkulator Pecahan', 'vi': 'Máy tính phân số', 'th': 'เครื่องคำนวณเศษส่วน', 'pl': 'Kalkulator ułamków', 'uk': 'Калькулятор дробів', 'ro': 'Calculator fracții', 'el': 'Υπολογισμός κλασμάτων', 'sv': 'Bråkräknare', 'no': 'Brøkkalkulator', 'da': 'Brøkregner', 'fi': 'Murtolukulaskuri', 'cs': 'Zlomková kalkulačka', 'hu': 'Törtkalkulátor', 'he': 'מחשבון שברים', 'ms': 'Kalkulator Pecahan', 'bn': 'ভগ্নাংশ ক্যালকুলেটর', 'ta': 'பின்ன கால்குலேட்டர்', 'te': 'భిన్నం కాల్కులేటర్', 'mr': 'અપૂર્ણાંક કેલ્ક્યુલેટર', 'gu': 'અપૂર્ણાંક કેલ્ક્યુલેટર', 'pa': 'ਭਿੰਨ ਕੈਲਕੁਲੇਟਰ', 'ur': 'کسر کیلکولیٹر', 'fa': 'ماشین حساب کسر', 'tl': 'Kalkulator ng Fraction'
  },
  'ratio': {
    'en': 'Ratio Calculator', 'es': 'Calculadora de Razones', 'hi': 'अनुपात कैलकुलेटर', 'fr': 'Calculatrice de Ratios', 'pt': 'Calculadora de Razão', 'de': 'Verhältnisrechner', 'ar': 'حاسبة النسب', 'ja': '比率電卓',
    'zh-cn': '比例计算器', 'zh-tw': '比例計算器', 'ru': 'Калькулятор пропорций', 'it': 'Calcolo rapporti', 'nl': 'Verhoudingen berekenen', 'tr': 'Oran Hesaplama', 'ko': '비율 계산기', 'id': 'Kalkulator Rasio', 'vi': 'Máy tính tỷ lệ', 'th': 'เครื่องคำนวณอัตราส่วน', 'pl': 'Kalkulator proporcji', 'uk': 'Калькулятор пропорцій', 'ro': 'Calculator rapoarte', 'el': 'Υπολογισμός αναλογιών', 'sv': 'Förhållanderäknare', 'no': 'Forholdskalkulator', 'da': 'Forholdsregner', 'fi': 'Suhdelaskuri', 'cs': 'Poměrová kalkulačka', 'hu': 'Aránykalkulátor', 'he': 'מחשבון יחסים', 'ms': 'Kalkulator Nisbah', 'bn': 'অনুপাত ক্যালকুলেটর', 'ta': 'விகித கால்குலேட்டர்', 'te': 'నిష్పత్తి కాల్కులేటర్', 'mr': 'ગુણોત્તર કેલ્ક્યુલેટર', 'gu': 'ગુણોત્તર કેલ્ક્યુલેટર', 'pa': 'ਅਨੁਪਾਤ ਕੈਲਕੁਲੇਟਰ', 'ur': 'تناسب کیلکولیٹر', 'fa': 'ماشین حساب نسبت', 'tl': 'Kalkulator ng Ratio'
  },
  'unit-prefix': {
    'en': 'Unit Prefix Converter', 'es': 'Prefijos de Unidades', 'hi': 'इकाई उपसर्ग कनवर्टर', 'fr': "Préfixe d'Unité", 'pt': 'Prefixo de Unidade', 'de': 'Einheitenpräfix-Umrechner', 'ar': 'محول بادئة الوحدات', 'ja': '単位接頭辞変換器',
    'zh-cn': '单位前缀转换器', 'zh-tw': '單位前綴轉換器', 'ru': 'Приставки единиц', 'it': 'Prefissi delle unità', 'nl': 'Eenhedenvoorvoegsel omrekenen', 'tr': 'Birim Öneki Dönüştürücü', 'ko': '단위 접두사 변환기', 'id': 'Konverter Prefiks Satuan', 'vi': 'Bộ chuyển đổi tiền tố đơn vị', 'th': 'เครื่องแปลงคำอุปสรรคหน่วย', 'pl': 'Konwerter przedrostków jednostek', 'uk': 'Префікси одиниць вимірювання', 'ro': 'Convertor prefixe unități', 'el': 'Μετατροπέας προθεμάτων μονάδων', 'sv': 'Prefixkonverterare', 'no': 'Prefikskonverterer', 'da': 'Præfiksomregner', 'fi': 'Yksikköetuliitemuunnin', 'cs': 'Převodník předpon jednotek', 'hu': 'Mértékegység-előtag átváltó', 'he': 'ממיר קידומות יחידות', 'ms': 'Penukar Prefiks Unit', 'bn': 'ইউনিট প্রিফিক্স রূপান্তরকারী', 'ta': 'அலகு முன்னொட்டு மாற்றி', 'te': 'యూనిట్ ప్రిఫిక్స్ మార్పిడి', 'mr': 'युनिट प्रीफिक्स कनवर्टर', 'gu': 'યુનિટ પ્રીફિક્સ કન્વર્ટર', 'pa': 'ਇਕਾਈ ਅਗੇਤਰ ਕਨਵਰਟਰ', 'ur': 'یونٹ پرفیکس کنورٹر', 'fa': 'مبدل پیشوند واحدها', 'tl': 'Tagasalin ng Prefix ng Unit'
  },
  'number-system': {
    'en': 'Number System Converter', 'es': 'Sistemas Numéricos', 'hi': 'संख्या प्रणाली कनवर्टर', 'fr': 'Systèmes de Nombres', 'pt': 'Sistemas Numéricos', 'de': 'Zahlensystem-Umrechner', 'ar': 'محول نظام الأعداد', 'ja': '数系変換器',
    'zh-cn': '数系转换器', 'zh-tw': '數系轉換器', 'ru': 'Системы счисления', 'it': 'Sistemi di numerazione', 'nl': 'Talstelsels omrekenen', 'tr': 'Sayı Sistemleri Dönüştürücü', 'ko': '수체계 변환기', 'id': 'Konverter Sistem Bilangan', 'vi': 'Bộ chuyển đổi hệ thống số', 'th': 'เครื่องแปลงระบบจำนวน', 'pl': 'Konwerter systemów liczbowych', 'uk': 'Конвертер систем числення', 'ro': 'Convertor sisteme de numerație', 'el': 'Μετατροπέας συστημάτων αριθμών', 'sv': 'Talsystemskonverterare', 'no': 'Tallsystemkonverterer', 'da': 'Talsystemomregner', 'fi': 'Lukujärjestelmämuunnin', 'cs': 'Převodník číselných soustav', 'hu': 'Számrendszer átváltó', 'he': 'ממיר מערכות מספרים', 'ms': 'Penukar Sistem Nombor', 'bn': 'সংখ্যা পদ্ধতি রূপান্তরকারী', 'ta': 'எண் முறைமை மாற்றி', 'te': 'సంఖ్యా వ్యవస్థ మార్పిడి', 'mr': 'નંબર સિસ્ટમ કન્વર્ટર', 'gu': 'નંબર સિસ્ટમ કન્વર્ટર', 'pa': 'ਸੰਖਿਆ ਪ੍ਰਣਾਲੀ ਕਨਵਰਟਰ', 'ur': 'نمبر سسٹم کنورٹر', 'fa': 'مبدل دستگاه‌های عددی', 'tl': 'Tagasalin ng System ng Numero'
  }
};

// Read the existing file
let content = fs.readFileSync(filePath, 'utf8');

// Generate the TS string for categoryTranslations
function formatTranslations(obj, indent = '') {
  let result = '';
  const keys = Object.keys(obj);
  for (let i = 0; i < keys.length; i++) {
    const k = keys[i];
    const langs = obj[k];
    const langKeys = Object.keys(langs);
    result += `${indent}  '${k}': {\n`;
    // Split into first line and subsequent lines
    const firstLineLangs = langKeys.slice(0, 8);
    const restLangs = langKeys.slice(8);
    
    let firstLine = '';
    for (const lk of firstLineLangs) {
      firstLine += `'${lk}': '${langs[lk].replace(/'/g, "\\'")}', `;
    }
    firstLine = firstLine.replace(/, $/, '');
    result += `${indent}    ${firstLine},\n`;
    
    if (restLangs.length > 0) {
      let secondLine = '';
      for (const lk of restLangs) {
        secondLine += `'${lk}': '${langs[lk].replace(/'/g, "\\'")}', `;
      }
      secondLine = secondLine.replace(/, $/, '');
      result += `${indent}    ${secondLine}\n`;
    }
    
    result += `${indent}  }`;
    if (i < keys.length - 1) result += ',';
    result += '\n';
  }
  return result;
}

const tsBlock = `export const categoryTranslations: Record<string, Record<string, string>> = {\n${formatTranslations(categoryTranslations, '')}};\n`;

// Find the insertion point: after '};' closing uiTranslations, before '\n\n// Common unit translations'
const marker = '\n// Common unit translations mapping (helps render dropdown options and landing pages)';
const insertPos = content.indexOf(marker);

if (insertPos === -1) {
  console.error("Could not find insertion marker");
  process.exit(1);
}

// Insert before the marker
const before = content.slice(0, insertPos + 1); // include the newline before marker
const after = content.slice(insertPos + 1);
const updatedContent = before + '\n' + tsBlock + after;

fs.writeFileSync(filePath, updatedContent, 'utf8');
console.log("Successfully injected categoryTranslations!");
